= IDN Role Code Vocabulary

This repository contains the Role Codes, that is the types of roles Agents - People and Organisations - play in relation to data, used by the https://mspgh.unimelb.edu.au/centres-institutes/centre-for-health-equity/research-group/indigenous-data-network[Indigenous Data Network (IDN)].

These Role Codes are presented in a Semantic Web vocabulary that is an extension to the ISO' Geospatial Metadata standard's http://iso.kurrawong.net/vocab/CI_RoleCode[CI Role Codes] vocabulary (also known as a codelist) that is also available online in Semantic Web form.

This vocabulary is available online at a persistent web location:

**https://linked.data.gov.au/def/idn-role-codes**


== License & Rights

The contents of this repository is licensed under Creative Commons 4.0 International. See the LICENSE file in the repository for details. Note that much of the content of this vocabulary is taken directly from the ISO's CI Role Codes codelist.


== Contacts

For technical enquiries:

**Jamie Feiss** +
*Data Infrastructure Developer* +
Indigenous Data Network +
University of Melbourne +
jamie.feiss@unimelb.edu.au

For policy:

**Levi Murray** +
*Strategic Data Manager* +
Indigenous Data Network +
University of Melbourne +
levi.murray@unimelb.edu.au
